- name: play with variables from files
  hosts: local
  connection: local  
  
  tasks:
  - name: playing with variables method overloading
    vars:
        COURSE: Ansible
    ansible.builtin.debug:
      msg: "hi! we have started course:: {{ COURSE }}, for a duration of ::{{ DURATION }} and instructed would be {{ TRAINER }}"
  - name: playing with variables
    ansible.builtin.debug:
      msg: "hi! we have started course:: {{ COURSE }}, for a duration of ::{{ DURATION }} and instructed would be {{ TRAINER }}"
  
  