- name: variables from prompt
  hosts: local
  connection: local
  tasks:
  - name: printing variables from the prompt
    ansible.builtin.debug:
      msg: "hi! we have started course:: {{ COURSE }}, for a duration of ::{{ DURATION }} and instructed would be {{ TRAINER }}"


# ansible-playbook -i inventory.ini -e ansible_username=ec2-user -e ansible_password=DevOps321 -e COURSE="anisble" -e DURATION="10 hrs" -e TRAINER="siva"