- name: install nginx
  hosts: dynamic_frontend
  become: yes
  serial: 2
  tasks:
  - name: nginx install in frontend servers
    ansible.builtin.dnf:
      name: nginx
      state: installed
  - name: run the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes